### ISSUE TITLE
npm run watch & npm run server 扫描二维码，手机上出现一个二维码让扫

### ISSUE THREAD

**Issue by mynane** [l455202325/APIDemo#1]

**Comment by l455202325** [comment]
不明白你想要问什么？
快应用开发时手机上需要同时安装 [快应用平台正式版预览](https://statres.quickapp.cn/quickapp/quickapp/201803/file/quickapp_platform_preview_release.apk) 和 [快应用调试器](https://statres.quickapp.cn/quickapp/quickapp/201803/file/quickapp_debugger.apk) 两个apk安装包，并且这两个都需安装，当你在命令行 输入npm run server后，如果没有问题， 就会在命令行出现一个供你扫描的二维码，这时候你打开手机的调试工具选择扫码安装，就可以扫描那个二维码了
