### ISSUE TITLE
代码有点冗余

### ISSUE THREAD

**Issue by wiikzz** [l455202325/APIDemo#2]
node_modules这个文件夹没有必要传
最好留一个rpk文件

**Comment by l455202325** [comment]
恩 是的 考虑到这个是入门级别的API Demo 是按照 每个功能模块单独一个一个引入的，功能也是一个一个慢慢开发的，所以代码肯定有冗余的，以后会出一个 优化升级版的，代码已将在编写中了，界面也会变得更美观
